# Generated by Django 3.2.12 on 2024-07-10 11:53

from django.db import migrations
import phonenumbers


def update_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        try:
            phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        except phonenumbers.NumberParseException:
            phone_number = phonenumbers.phonenumber.PhoneNumber()
        possible_number = phonenumbers.is_possible_number(phone_number)
        valid_number = phonenumbers.is_valid_number(phone_number)
        if possible_number and valid_number:
            normalized_phone_number = phonenumbers.format_number(phone_number,
                                                                 phonenumbers.PhoneNumberFormat.E164)
            flat.owner_pure_phone = normalized_phone_number 
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [migrations.RunPython(update_owner_pure_phone)
    ]
